
spring:
  datasource:
    username: root
    password: 12345
    url: jdbc:mysql://localhost:3306/userdb1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
server:
  port: 9192

  # npm i react-router-dom
  #npm install bootstrap
    #npm i react-icons